version: "3"
services:
  node-app:
    container_name: app-06
    image: sh3poz/node-app01
    env_file:
      - ./.env
    deploy:
      replicas: 4
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-dp:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: example
  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8080:80"
    depends_on:
      - node-app
  
volumes:
   mongo-db:
   postgres-dp:



      


