FROM node:14 as base

FROM base as development

WORKDIR /app
COPY package.json .
ARG NODE_ENV
RUN npm install
ENV PORT=4000
COPY . .
EXPOSE ${PORT}
CMD [ "npm", "run", "start-dev" ]

FROM base as production

WORKDIR /app
COPY package.json .
ARG NODE_ENV
RUN npm install --only=production
ENV PORT=4000
COPY . .
EXPOSE ${PORT}
CMD [ "npm", "start" ]