FROM node:14

WORKDIR /app

COPY package.json .

ARG NODE_ENV

RUN if ["$NODE_ENV" = "production" ]; \
    then npm install --only=production; \
    else npm install; \
    fi
    
RUN npm install

ENV PORT=4000

COPY . .

EXPOSE ${PORT}

CMD [ "npm","run", "start-dev" ]
