version: "3"
services:
  node-app:
    container_name: app-06
    volumes:
      - C:\Users\Hassan\Desktop\node-app\source:/app/source:ro
    ports:
      - "4000:4000"
    env_file:
      - C:\Users\Hassan\Desktop\node-app\.env
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    

      


